---
  metaData: 
    author: "d3fkon"
    git-repo: "https://github.com/d3fkon/templateaspipelein"
    approval: 
      approved-by: "d3fkon"
      approval-date: 1564467203284
  job: 
    job-name: "d3fkonxtemplateaspipelein"
    config: 
      pre-unit-test: "yes"
      post-unit-test: "yes"
      dev: "no"
      prod: "yes"
      fresh: "yes"
